spring:
  # DB 연결
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-database/lan-line-elder-demo
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update # 바뀔수 있음. DB 고정으로 등록해두려면 이거 변경
logging:
  level:
    org.hibernate.type: trace
