spring:
  # DB 연결
#    h2 DB
#  datasource:
#      url: jdbc:h2:tcp://localhost/~/h2-database/lan-line-elder-demo
#    driver-class-name: org.h2.Driver
#    username: sa



  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: validate # 바뀔수 있음. DB 고정으로 등록해두려면 이거 변경
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org.hibernate.type: trace




